### PR TITLE
Add JSON output option

### PR DESCRIPTION
**Pull request by frrad**
PR 1/2 for https://github.com/banool/recreation-gov-campsite-checker/issues/5 

Adds a `--output` flag with default option `text` (gives the normal behavior) and additional option `json` which causes the json formatted results to be printed to stdout.

### CODE REVIEW

**Comment by frrad** [comment]
This is still a WIP since I need to install Python 3.7 and run the formatter.

**Comment by frrad** [comment]
This is ready for review now when you get a chance.

**Comment by banool** [comment]
Sorry just got a chance to look at this. The diff looks reasonable, feel free to fix it up and I'll merge it in.

**Comment by banool** [comment]
Okay no response for a while so I'm going to close this out. If you want to add this functionality later feel free to open a new pull request.

**Pull request closed without merging**
